<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>E2 Challenge</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    </head>
    <body>
        <h1>Matches</h1>
        <div class="container-fluid">
            <?php foreach ($matchDates as $date => $matchDateData ) { ?>
            <div class="card card-body">
                <p>
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample<?php echo htmlspecialchars($date); ?>" aria-expanded="false" aria-controls="collapseExample<?php echo htmlspecialchars($date); ?>">
                        <?php echo htmlspecialchars($matchDateData['matchDate']); ?>
                    </button>
                </p>
                <div class="collapse" id="collapseExample<?php echo htmlspecialchars($date); ?>">
                    <div class="card card-body">
                        <ul class="list-group">
                            <?php
                            /**
                             * @var \Widget\Models\Match $match
                             */
                            foreach ($matchDateData['data'] as $match) {
                                ?>
                            <li class="list-group-item">
                                <span><?php echo $match->getMatchDate()->format('H:i') ?> </span>
                                <span> <img src="<?php echo $imageRenderer($match->getHomeTeam()); ?>" /> <?php echo htmlspecialchars($match->getHomeTeam()->getName()); ?> : <?php echo htmlspecialchars($match->getAwayTeam()->getName()); ?> <img src="<?php echo $imageRenderer($match->getAwayTeam()); ?>" />
                                </span>
                                <span><?php echo htmlspecialchars($match->getCompetition()->getName()) . ' (' . htmlspecialchars($match->getCompetition()->getGlobalImportance()) . ')' ?> </span>
                            </li>
                                <?php
                            }
                            ?>
                        </ul>
                    </div>
                </div>
            </div>
            <?php } ?>
        </div>

    </body>
</html>
